# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'EnvironmentName' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: Create Environment
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: True
  - task: PowerPlatformToolInstaller@2
    displayName: 'Power Platform Tool Installer '
  - task: PowerPlatformCreateEnvironment@2
    displayName: 'Power Platform Create Environment '
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: 56c8c346-e127-479a-bdac-6cd4d94da5d4
      DisplayName: $(EnvironmentName)
      DomainName: $(EnvironmentName)
...
