# This is a basic workflow to help you get started with Actions
name: Export Solution From Dev and Add to Source Control
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: ALMLab
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Commit:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Install Power Platform tools for working with solutions
      - name: Power Platform Tool Installer
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: 'who-am-i'
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: 'https://alyousse.crm.dynamics.com'
          app-id: ${{ secrets.CRM_ONLINE_USER }}
          client-secret: ${{ secrets.CRM_ONLINE_PWD }}
          tenant-id: '1557f771-4c8e-4dbd-8b80-dd00a88e833e'
        
      # Export Solution with variable
      - name: Power Platform Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://alyousse.crm.dynamics.com'
          app-id: ${{ secrets.CRM_ONLINE_USER }}
          client-secret: ${{ secrets.CRM_ONLINE_PWD }}
          tenant-id: '1557f771-4c8e-4dbd-8b80-dd00a88e833e'
          #user-name: ${{ secrets.CARGO_CRM_USER }}
          #password-secret: ${{ secrets.CARGO_CRM_PASSWD }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

          
      # Unpack solution to working folder
      - name: Power Platform Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: branch-solution, prepare it for a PullRequest
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
